project:
  type: website
  output-dir: docs

website:
  title: "MaineR Users Group"
  navbar: 
    background: "#b17ed8"  #*background color 
    foreground: "white"
    logo: "maine_r_user_logo.png"
    right:
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: ayu # "#7030a0"  dark purple
    code-line-numbers: true

editor: visual

